
class UnitError(Exception):
    pass

class DataError(Exception):
    pass
